# Generated by Django 3.0.6 on 2020-05-29 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('posts', '0002_auto_20200529_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Perfil'),
        ),
    ]
